//! Renders the game data as Rust source.
//!
//! The output is laid out by hand, one entry per line, so that a version update is a
//! readable diff. The crates include it under `#[rustfmt::skip]`.

use std::fmt::Write;
use std::path::PathBuf;

use anyhow::{Result, ensure};

use crate::model::GameData;

/// Directories that hold nothing but generated files, relative to the workspace root.
pub const DIRECTORIES: [&str; 2] = [DATA_DIR, PROTOCOL_DIR];

const DATA_DIR: &str = "crates/clustine-data/src/generated";
const PROTOCOL_DIR: &str = "crates/clustine-protocol/src/generated";

const LINE_WIDTH: usize = 100;

/// A generated source file.
pub struct Output {
    /// Relative to the workspace root.
    pub path: PathBuf,
    pub content: String,
}

pub fn all(data: &GameData) -> Result<Vec<Output>> {
    let mut outputs = Vec::new();
    let mut add = |dir: &str, name: &str, body: String| {
        outputs.push(Output {
            path: PathBuf::from(dir).join(name),
            content: format!(
                "// Generated by `cargo datagen` from Minecraft {}. Do not edit.\n\n{body}",
                data.version.id
            ),
        });
    };

    add(
        DATA_DIR,
        "mod.rs",
        modules(&[
            "blocks",
            "dimension_types",
            "entity_types",
            "items",
            "registries",
            "tags",
            "version",
        ]),
    );
    add(DATA_DIR, "version.rs", version(data));
    add(DATA_DIR, "blocks.rs", blocks(data)?);
    add(DATA_DIR, "items.rs", items(data)?);
    add(DATA_DIR, "entity_types.rs", entity_types(data)?);
    add(DATA_DIR, "registries.rs", registries(data));
    add(DATA_DIR, "dimension_types.rs", dimension_types(data));
    add(DATA_DIR, "tags.rs", tags(data));

    add(PROTOCOL_DIR, "mod.rs", modules(&["packet_ids"]));
    add(PROTOCOL_DIR, "packet_ids.rs", packet_ids(data)?);
    Ok(outputs)
}

fn modules(names: &[&str]) -> String {
    names
        .iter()
        .map(|name| format!("pub mod {name};\n"))
        .collect()
}

fn version(data: &GameData) -> String {
    let version = &data.version;
    format!(
        "pub const GAME_VERSION: &str = {:?};\n\
         pub const PROTOCOL_VERSION: i32 = {};\n\
         pub const DATA_VERSION: i32 = {};\n",
        version.id, version.protocol, version.data
    )
}

fn blocks(data: &GameData) -> Result<String> {
    let state_count = data.blocks.last().map_or(0, |block| block.last_state + 1);
    let mut out = String::new();
    writeln!(out, "use crate::{{Block, BlockState}};\n")?;
    writeln!(out, "pub const BLOCK_STATE_COUNT: u32 = {state_count};\n")?;
    writeln!(out, "pub static BLOCKS: [Block; {}] = [", data.blocks.len())?;
    for block in &data.blocks {
        writeln!(
            out,
            "    Block {{ name: {:?}, first_state: BlockState({}), last_state: BlockState({}), \
             default_state: BlockState({}) }},",
            block.name, block.first_state, block.last_state, block.default_state
        )?;
    }
    writeln!(out, "];\n")?;
    writeln!(out, "pub mod default_states {{")?;
    writeln!(out, "    use crate::BlockState;\n")?;
    for block in &data.blocks {
        writeln!(
            out,
            "    pub const {}: BlockState = BlockState({});",
            constant_name(&block.name)?,
            block.default_state
        )?;
    }
    writeln!(out, "}}")?;
    Ok(out)
}

fn items(data: &GameData) -> Result<String> {
    let mut out = String::new();
    writeln!(out, "use crate::{{BlockState, Item}};\n")?;
    writeln!(out, "pub static ITEMS: [Item; {}] = [", data.items.len())?;
    for item in &data.items {
        let block = match item.block {
            Some(state) => format!("Some(BlockState({state}))"),
            None => "None".to_owned(),
        };
        writeln!(out, "    Item {{ name: {:?}, block: {block} }},", item.name)?;
    }
    writeln!(out, "];\n")?;
    let names = data.items.iter().map(|item| item.name.as_str());
    out.push_str(&id_constants(names)?);
    Ok(out)
}

fn entity_types(data: &GameData) -> Result<String> {
    let mut out = String::new();
    writeln!(
        out,
        "pub static ENTITY_TYPES: [&str; {}] = [",
        data.entity_types.len()
    )?;
    for name in &data.entity_types {
        writeln!(out, "    {name:?},")?;
    }
    writeln!(out, "];\n")?;
    out.push_str(&id_constants(data.entity_types.iter().map(String::as_str))?);
    Ok(out)
}

/// A module of `i32` constants, one per name, numbered by position.
fn id_constants<'a>(names: impl Iterator<Item = &'a str>) -> Result<String> {
    let mut out = String::from("pub mod ids {\n");
    for (id, name) in names.enumerate() {
        writeln!(out, "    pub const {}: i32 = {id};", constant_name(name)?)?;
    }
    out.push_str("}\n");
    Ok(out)
}

fn registries(data: &GameData) -> String {
    let mut out = String::from("use crate::Registry;\n\n");
    out.push_str(&format!(
        "pub static SYNCED_REGISTRIES: [Registry; {}] = [\n",
        data.synced_registries.len()
    ));
    for registry in &data.synced_registries {
        out.push_str("    Registry {\n");
        out.push_str(&format!("        name: \"minecraft:{}\",\n", registry.name));
        out.push_str("        entries: &[\n");
        for entry in &registry.entries {
            out.push_str(&format!("            {entry:?},\n"));
        }
        out.push_str("        ],\n    },\n");
    }
    out.push_str("];\n");
    out
}

fn dimension_types(data: &GameData) -> String {
    let mut out = String::from("use crate::DimensionType;\n\n");
    out.push_str(&format!(
        "pub static DIMENSION_TYPES: [DimensionType; {}] = [\n",
        data.dimension_types.len()
    ));
    for dimension in &data.dimension_types {
        out.push_str(&format!(
            "    DimensionType {{ name: {:?}, min_y: {}, height: {} }},\n",
            dimension.name, dimension.min_y, dimension.height
        ));
    }
    out.push_str("];\n");
    out
}

fn tags(data: &GameData) -> String {
    let mut out = String::from("use crate::{RegistryTags, Tag};\n\n");
    out.push_str(&format!(
        "pub static TAGS: [RegistryTags; {}] = [\n",
        data.tags.len()
    ));
    for registry in &data.tags {
        out.push_str("    RegistryTags {\n");
        out.push_str(&format!(
            "        registry: \"minecraft:{}\",\n",
            registry.registry
        ));
        out.push_str("        tags: &[\n");
        for tag in &registry.tags {
            out.push_str("            Tag {\n");
            out.push_str(&format!("                name: {:?},\n", tag.name));
            if tag.entries.is_empty() {
                out.push_str("                entries: &[],\n");
            } else {
                out.push_str("                entries: &[\n");
                out.push_str(&wrapped(&tag.entries, "                    "));
                out.push_str("                ],\n");
            }
            out.push_str("            },\n");
        }
        out.push_str("        ],\n    },\n");
    }
    out.push_str("];\n");
    out
}

fn packet_ids(data: &GameData) -> Result<String> {
    let mut out = String::new();
    let mut open_state = None;
    for set in &data.packets {
        if open_state != Some(set.state) {
            if open_state.is_some() {
                out.push_str("}\n\n");
            }
            writeln!(out, "pub mod {} {{", set.state)?;
            open_state = Some(set.state);
        } else {
            out.push('\n');
        }
        writeln!(out, "    pub mod {} {{", set.direction)?;
        for (id, name) in set.packets.iter().enumerate() {
            let constant = constant_name(name)?;
            ensure!(
                constant != "NAMES",
                "packet {name} collides with the NAMES table"
            );
            writeln!(out, "        pub const {constant}: i32 = {id};")?;
        }
        writeln!(
            out,
            "\n        pub static NAMES: [&str; {}] = [",
            set.packets.len()
        )?;
        for name in &set.packets {
            writeln!(out, "            {name:?},")?;
        }
        out.push_str("        ];\n    }\n");
    }
    if open_state.is_some() {
        out.push_str("}\n");
    }
    Ok(out)
}

/// `minecraft:grass_block` becomes `GRASS_BLOCK`, `minecraft:debug/event` becomes `DEBUG_EVENT`.
fn constant_name(identifier: &str) -> Result<String> {
    let name = identifier.strip_prefix("minecraft:").unwrap_or(identifier);
    let name = name.replace('/', "_");
    let valid = name.starts_with(|c: char| c.is_ascii_lowercase() || c == '_')
        && name
            .chars()
            .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '_');
    ensure!(valid, "{identifier} cannot be turned into a constant name");
    Ok(name.to_ascii_uppercase())
}

/// Comma-separated numbers, wrapped to the line width, each line starting with `indent`.
fn wrapped(numbers: &[usize], indent: &str) -> String {
    let mut out = String::new();
    let mut line = String::new();
    for number in numbers {
        let item = format!("{number},");
        if !line.is_empty() && indent.len() + line.len() + 1 + item.len() > LINE_WIDTH {
            out.push_str(indent);
            out.push_str(&line);
            out.push('\n');
            line.clear();
        }
        if !line.is_empty() {
            line.push(' ');
        }
        line.push_str(&item);
    }
    if !line.is_empty() {
        out.push_str(indent);
        out.push_str(&line);
        out.push('\n');
    }
    out
}
