//! Renders the game data as the committed output: Rust source and packed tables.
//!
//! Rust is laid out here, by hand, one entry per line, so that a version update is a
//! readable diff; it is never passed through a formatter, so its bytes do not depend on
//! a toolchain. The crates include it under `#[rustfmt::skip]`. What is thousands of
//! rows of one shape is packed instead (`tables.rs`). See
//! `docs/adr/0019-data-made-from-mojangs-jar.md`, sections 1 and 3.

use std::collections::BTreeSet;
use std::fmt::Write;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result, ensure};

use crate::jar::SERVER_JAR;
use crate::model::{GameData, Property};
use crate::{packed, sums, tables};

/// Directories that hold nothing but generated files, relative to the workspace root.
///
/// ADR-0019 names two more, of the crate of world-generation data, which come with
/// that crate.
pub const DIRECTORIES: [&str; 2] = [DATA_DIR, PROTOCOL_DIR];

const DATA_DIR: &str = "crates/clustine-data/src/generated";
const PROTOCOL_DIR: &str = "crates/clustine-protocol/src/generated";

const LINE_WIDTH: usize = 100;

/// The most that all committed generated output may come to, in bytes: the generated
/// directories and the sums (ADR-0019, section 6).
pub const TOTAL_BUDGET: usize = 6_000_000;

/// The file in each generated directory that says whose the data in it is. Packed
/// tables carry no comment, so the directory does.
pub const NOTICE_FILE: &str = "NOTICE";

/// The first line of every generated Rust file, for the game version `version`.
pub fn head(version: &str) -> String {
    format!(
        "// Generated by cargo datagen from Minecraft {version}. Do not edit. The data in this \
         file is Mojang's and not under the AGPL; the code around it is: see NOTICE.md."
    )
}

/// A generated file.
pub struct Output {
    /// Relative to the workspace root, with `/` between its parts.
    pub path: PathBuf,
    pub content: Vec<u8>,
}

/// Every committed output, the sums last. `root` is the workspace, whose files the
/// sums take the hashes of datagen's own inputs from.
pub fn all(data: &GameData, root: &Path) -> Result<Vec<Output>> {
    let mut outputs = generated(data)?;
    let sums = sums::render(
        SERVER_JAR.sha1,
        &sums::inputs(root)?,
        outputs
            .iter()
            .map(|output| (output.path.as_path(), output.content.as_slice())),
    )?;
    outputs.push(Output {
        path: PathBuf::from(sums::PATH),
        content: sums.into_bytes(),
    });
    check_budget(&outputs, TOTAL_BUDGET)?;
    Ok(outputs)
}

/// Fails if `outputs` come to more than `budget` bytes, so that nothing over budget is
/// ever written.
pub fn check_budget(outputs: &[Output], budget: usize) -> Result<()> {
    let total: usize = outputs.iter().map(|output| output.content.len()).sum();
    ensure!(
        total <= budget,
        "the generated output comes to {total} bytes, over the budget of {budget} \
         (docs/adr/0019-data-made-from-mojangs-jar.md, section 6)"
    );
    Ok(())
}

/// The files of the generated directories.
fn generated(data: &GameData) -> Result<Vec<Output>> {
    let mut outputs = Vec::new();
    let version = data.version.id.as_str();
    let mut add = |dir: &str, name: &str, body: String| {
        outputs.push(Output {
            path: PathBuf::from(dir).join(name),
            content: format!("{}\n\n{body}", head(version)).into_bytes(),
        });
    };

    add(
        DATA_DIR,
        "mod.rs",
        modules(&[
            "block_classes",
            "block_properties",
            "blocks",
            "dimension_types",
            "entity_types",
            "items",
            "registries",
            "tags",
            "version",
        ]),
    );
    add(DATA_DIR, "version.rs", version_file(data)?);
    add(DATA_DIR, "blocks.rs", blocks(data)?);
    add(DATA_DIR, "block_properties.rs", block_properties(data)?);
    add(DATA_DIR, "block_classes.rs", block_classes(data)?);
    add(DATA_DIR, "items.rs", items(data)?);
    add(DATA_DIR, "entity_types.rs", entity_types(data)?);
    add(DATA_DIR, "registries.rs", registries(data));
    add(DATA_DIR, "dimension_types.rs", dimension_types(data));
    add(DATA_DIR, "tags.rs", tags(data));

    add(PROTOCOL_DIR, "mod.rs", modules(&["packet_ids"]));
    add(PROTOCOL_DIR, "packet_ids.rs", packet_ids(data)?);

    outputs.push(Output {
        path: PathBuf::from(DATA_DIR).join("block_states.bin"),
        content: tables::block_states(
            &data.extract.states,
            &data.blocks,
            &data.block_tag("minecraft:blocks_motion_in_heightmap")?,
            &data.block_tag("minecraft:blocks_motion_in_heightmap_no_leaves")?,
            data.fluids.len(),
            SERVER_JAR.sha1,
        )
        .context("packing block_states.bin")?,
    });
    outputs.push(Output {
        // ADR-0019 puts this table into the crate of world-generation data; until
        // that crate exists it is kept beside the block states.
        path: PathBuf::from(DATA_DIR).join("biome_parameters.bin"),
        content: tables::biome_parameters(
            &data.extract.biome_parameters,
            &data.biome_reports,
            data.biomes()?,
            SERVER_JAR.sha1,
        )
        .context("packing biome_parameters.bin")?,
    });

    for directory in DIRECTORIES {
        let notice = notice(version, directory, &outputs);
        outputs.push(Output {
            path: PathBuf::from(directory).join(NOTICE_FILE),
            content: notice.into_bytes(),
        });
    }
    Ok(outputs)
}

/// The notice of a generated directory: whose the data is, and the files it covers.
fn notice(version: &str, directory: &str, outputs: &[Output]) -> String {
    let mut names: Vec<String> = outputs
        .iter()
        .filter_map(|output| output.path.strip_prefix(directory).ok())
        .map(|name| name.to_string_lossy().replace('\\', "/"))
        .collect();
    names.sort();
    let mut out = format!(
        "Generated by cargo datagen from Minecraft {version}. Do not edit. The data in the files\n\
         of this directory is Mojang's and not under the AGPL; the code around it is: see\n\
         NOTICE.md at the root of the repository.\n\n\
         The files, of which the packed tables (*.bin) can carry no such line themselves:\n\n"
    );
    for name in names {
        out.push_str("  ");
        out.push_str(&name);
        out.push('\n');
    }
    out
}

fn modules(names: &[&str]) -> String {
    names
        .iter()
        .map(|name| format!("pub mod {name};\n"))
        .collect()
}

fn version_file(data: &GameData) -> Result<String> {
    let version = &data.version;
    let sha1 = packed::sha1_bytes(SERVER_JAR.sha1)?;
    let bytes: Vec<String> = sha1.iter().map(|byte| format!("0x{byte:02x}")).collect();
    Ok(format!(
        "pub const GAME_VERSION: &str = {:?};\n\
         pub const PROTOCOL_VERSION: i32 = {};\n\
         pub const DATA_VERSION: i32 = {};\n\
         \n\
         /// The server jar these tables are made from, as Mojang publishes it.\n\
         pub const SERVER_JAR_URL: &str = {:?};\n\
         pub const SERVER_JAR_SHA1: &str = {:?};\n\
         pub const SERVER_JAR_SHA1_BYTES: [u8; 20] = [\n    {},\n    {},\n];\n",
        version.id,
        version.protocol,
        version.data,
        SERVER_JAR.url,
        SERVER_JAR.sha1,
        bytes[..10].join(", "),
        bytes[10..].join(", "),
    ))
}

/// The properties of every block: the distinct properties, the distinct lists of them,
/// which list each block has, and the blocks sorted by name.
fn block_properties(data: &GameData) -> Result<String> {
    let distinct: BTreeSet<&Property> = data
        .blocks
        .iter()
        .flat_map(|block| &block.properties)
        .collect();
    let properties: Vec<&Property> = distinct.into_iter().collect();
    let number = |property: &Property| {
        properties
            .binary_search(&property)
            .map_err(|_| anyhow::anyhow!("a property went missing"))
    };

    let mut lists: BTreeSet<Vec<usize>> = BTreeSet::new();
    let mut of_block = Vec::new();
    for block in &data.blocks {
        let list = block
            .properties
            .iter()
            .map(number)
            .collect::<Result<Vec<_>>>()?;
        lists.insert(list.clone());
        of_block.push(list);
    }
    let lists: Vec<Vec<usize>> = lists.into_iter().collect();
    let block_lists = of_block
        .iter()
        .map(|list| {
            lists
                .binary_search(list)
                .map_err(|_| anyhow::anyhow!("a list went missing"))
        })
        .collect::<Result<Vec<_>>>()?;

    let mut by_name: Vec<usize> = (0..data.blocks.len()).collect();
    by_name.sort_by(|&a, &b| data.blocks[a].name.cmp(&data.blocks[b].name));
    ensure!(
        properties.len() <= usize::from(u16::MAX) && lists.len() <= usize::from(u16::MAX),
        "the properties no longer fit 16-bit numbers"
    );

    let mut out = String::new();
    writeln!(out, "use crate::BlockProperty;\n")?;
    writeln!(
        out,
        "/// Every distinct property, by name and then by its values."
    )?;
    writeln!(
        out,
        "pub static PROPERTIES: [BlockProperty; {}] = [",
        properties.len()
    )?;
    for property in &properties {
        let values: Vec<String> = property
            .values
            .iter()
            .map(|value| format!("{value:?}"))
            .collect();
        writeln!(
            out,
            "    BlockProperty {{ name: {:?}, values: &[{}] }},",
            property.name,
            values.join(", ")
        )?;
    }
    writeln!(out, "];\n")?;
    writeln!(
        out,
        "/// Every distinct list of properties a block has, as numbers in `PROPERTIES`. The game"
    )?;
    writeln!(
        out,
        "/// numbers the states of a block by them, the first counting most."
    )?;
    writeln!(
        out,
        "pub static PROPERTY_LISTS: [&[u16]; {}] = [",
        lists.len()
    )?;
    for list in &lists {
        let numbers: Vec<String> = list.iter().map(usize::to_string).collect();
        writeln!(out, "    &[{}],", numbers.join(", "))?;
    }
    writeln!(out, "];\n")?;
    writeln!(
        out,
        "/// Which of `PROPERTY_LISTS` each block has, by block id."
    )?;
    writeln!(
        out,
        "pub static BLOCK_PROPERTY_LISTS: [u16; {}] = [",
        block_lists.len()
    )?;
    out.push_str(&wrapped(&block_lists, "    "));
    writeln!(out, "];\n")?;
    writeln!(
        out,
        "/// The ids of the blocks in the order of their names, to find a block by its name."
    )?;
    writeln!(
        out,
        "pub static BLOCKS_BY_NAME: [u16; {}] = [",
        by_name.len()
    )?;
    out.push_str(&wrapped(&by_name, "    "));
    writeln!(out, "];")?;
    Ok(out)
}

/// What the game's code says of every block (ADR-0019, table 4), with the names of the
/// fluids and of the block entity types that the tables number.
fn block_classes(data: &GameData) -> Result<String> {
    let dumped = &data.extract.blocks;
    ensure!(
        dumped.len() == data.blocks.len(),
        "the extract program wrote {} blocks, the report has {}",
        dumped.len(),
        data.blocks.len()
    );
    let classes: BTreeSet<&str> = dumped.iter().map(|block| block.class.as_str()).collect();
    for class in &classes {
        let valid = class.starts_with(|c: char| c.is_ascii_uppercase())
            && class.chars().all(|c| c.is_ascii_alphanumeric());
        ensure!(valid, "the class {class} cannot name a variant");
    }

    let mut out = String::new();
    writeln!(out, "use crate::BlockInfo;\n")?;
    writeln!(
        out,
        "/// The fluids by the game's ids, which a block state's row names its fluid by."
    )?;
    writeln!(out, "pub static FLUIDS: [&str; {}] = [", data.fluids.len())?;
    for name in &data.fluids {
        writeln!(out, "    {name:?},")?;
    }
    writeln!(out, "];\n")?;
    writeln!(out, "/// The block entity types by the game's ids.")?;
    writeln!(
        out,
        "pub static BLOCK_ENTITY_TYPES: [&str; {}] = [",
        data.block_entity_types.len()
    )?;
    for name in &data.block_entity_types {
        writeln!(out, "    {name:?},")?;
    }
    writeln!(out, "];\n")?;

    writeln!(
        out,
        "/// The classes of the game's blocks, by the simple names of the Java classes."
    )?;
    writeln!(
        out,
        "#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]"
    )?;
    writeln!(out, "pub enum BlockClass {{")?;
    for class in &classes {
        writeln!(out, "    {class},")?;
    }
    writeln!(out, "}}\n")?;

    writeln!(
        out,
        "// The table names the classes without their type, which its lines would repeat."
    )?;
    writeln!(out, "use self::BlockClass::*;\n")?;
    writeln!(
        out,
        "/// What the game's code says of each block, by block id."
    )?;
    writeln!(
        out,
        "pub static BLOCK_INFO: [BlockInfo; {}] = [",
        dumped.len()
    )?;
    for (block, dumped) in data.blocks.iter().zip(dumped) {
        ensure!(
            block.name == dumped.name,
            "the extract program has {} where the report has {}",
            dumped.name,
            block.name
        );
        let entity_type = match dumped.block_entity_type {
            Some(id) => {
                ensure!(
                    id < data.block_entity_types.len() && id <= usize::from(u8::MAX),
                    "{} has the block entity type {id}, which the registry lacks",
                    block.name
                );
                format!("Some({id})")
            }
            None => "None".to_owned(),
        };
        let name = block.name.strip_prefix("minecraft:").unwrap_or(&block.name);
        writeln!(
            out,
            "    BlockInfo {{ class: {}, block_entity_type: {entity_type}, \
             used_by_click: {} }}, // {name}",
            dumped.class, dumped.used_by_click
        )?;
    }
    writeln!(out, "];")?;
    Ok(out)
}

fn blocks(data: &GameData) -> Result<String> {
    let state_count = data.blocks.last().map_or(0, |block| block.last_state + 1);
    let mut out = String::new();
    writeln!(out, "use crate::{{Block, BlockState}};\n")?;
    writeln!(out, "pub const BLOCK_STATE_COUNT: u32 = {state_count};\n")?;
    writeln!(out, "pub static BLOCKS: [Block; {}] = [", data.blocks.len())?;
    for block in &data.blocks {
        writeln!(
            out,
            "    Block {{ name: {:?}, first_state: BlockState({}), last_state: BlockState({}), \
             default_state: BlockState({}) }},",
            block.name, block.first_state, block.last_state, block.default_state
        )?;
    }
    writeln!(out, "];\n")?;
    writeln!(out, "pub mod default_states {{")?;
    writeln!(out, "    use crate::BlockState;\n")?;
    for block in &data.blocks {
        writeln!(
            out,
            "    pub const {}: BlockState = BlockState({});",
            constant_name(&block.name)?,
            block.default_state
        )?;
    }
    writeln!(out, "}}")?;
    Ok(out)
}

fn items(data: &GameData) -> Result<String> {
    let mut out = String::new();
    writeln!(out, "use crate::{{BlockState, Item}};\n")?;
    writeln!(out, "pub static ITEMS: [Item; {}] = [", data.items.len())?;
    for item in &data.items {
        let block = match item.block {
            Some(state) => format!("Some(BlockState({state}))"),
            None => "None".to_owned(),
        };
        writeln!(out, "    Item {{ name: {:?}, block: {block} }},", item.name)?;
    }
    writeln!(out, "];\n")?;
    let names = data.items.iter().map(|item| item.name.as_str());
    out.push_str(&id_constants(names)?);
    Ok(out)
}

fn entity_types(data: &GameData) -> Result<String> {
    let mut out = String::new();
    writeln!(
        out,
        "pub static ENTITY_TYPES: [&str; {}] = [",
        data.entity_types.len()
    )?;
    for name in &data.entity_types {
        writeln!(out, "    {name:?},")?;
    }
    writeln!(out, "];\n")?;
    out.push_str(&id_constants(data.entity_types.iter().map(String::as_str))?);
    Ok(out)
}

/// A module of `i32` constants, one per name, numbered by position.
fn id_constants<'a>(names: impl Iterator<Item = &'a str>) -> Result<String> {
    let mut out = String::from("pub mod ids {\n");
    for (id, name) in names.enumerate() {
        writeln!(out, "    pub const {}: i32 = {id};", constant_name(name)?)?;
    }
    out.push_str("}\n");
    Ok(out)
}

fn registries(data: &GameData) -> String {
    let mut out = String::from("use crate::Registry;\n\n");
    out.push_str(&format!(
        "pub static SYNCED_REGISTRIES: [Registry; {}] = [\n",
        data.synced_registries.len()
    ));
    for registry in &data.synced_registries {
        out.push_str("    Registry {\n");
        out.push_str(&format!("        name: \"minecraft:{}\",\n", registry.name));
        out.push_str("        entries: &[\n");
        for entry in &registry.entries {
            out.push_str(&format!("            {entry:?},\n"));
        }
        out.push_str("        ],\n    },\n");
    }
    out.push_str("];\n");
    out
}

fn dimension_types(data: &GameData) -> String {
    let mut out = String::from("use crate::DimensionType;\n\n");
    out.push_str(&format!(
        "pub static DIMENSION_TYPES: [DimensionType; {}] = [\n",
        data.dimension_types.len()
    ));
    for dimension in &data.dimension_types {
        out.push_str(&format!(
            "    DimensionType {{ name: {:?}, min_y: {}, height: {} }},\n",
            dimension.name, dimension.min_y, dimension.height
        ));
    }
    out.push_str("];\n");
    out
}

fn tags(data: &GameData) -> String {
    let mut out = String::from("use crate::{RegistryTags, Tag};\n\n");
    out.push_str(&format!(
        "pub static TAGS: [RegistryTags; {}] = [\n",
        data.tags.len()
    ));
    for registry in &data.tags {
        out.push_str("    RegistryTags {\n");
        out.push_str(&format!(
            "        registry: \"minecraft:{}\",\n",
            registry.registry
        ));
        out.push_str("        tags: &[\n");
        for tag in &registry.tags {
            out.push_str("            Tag {\n");
            out.push_str(&format!("                name: {:?},\n", tag.name));
            if tag.entries.is_empty() {
                out.push_str("                entries: &[],\n");
            } else {
                out.push_str("                entries: &[\n");
                out.push_str(&wrapped(&tag.entries, "                    "));
                out.push_str("                ],\n");
            }
            out.push_str("            },\n");
        }
        out.push_str("        ],\n    },\n");
    }
    out.push_str("];\n");
    out
}

fn packet_ids(data: &GameData) -> Result<String> {
    let mut out = String::new();
    let mut open_state = None;
    for set in &data.packets {
        if open_state != Some(set.state) {
            if open_state.is_some() {
                out.push_str("}\n\n");
            }
            writeln!(out, "pub mod {} {{", set.state)?;
            open_state = Some(set.state);
        } else {
            out.push('\n');
        }
        writeln!(out, "    pub mod {} {{", set.direction)?;
        for (id, name) in set.packets.iter().enumerate() {
            let constant = constant_name(name)?;
            ensure!(
                constant != "NAMES",
                "packet {name} collides with the NAMES table"
            );
            writeln!(out, "        pub const {constant}: i32 = {id};")?;
        }
        writeln!(
            out,
            "\n        pub static NAMES: [&str; {}] = [",
            set.packets.len()
        )?;
        for name in &set.packets {
            writeln!(out, "            {name:?},")?;
        }
        out.push_str("        ];\n    }\n");
    }
    if open_state.is_some() {
        out.push_str("}\n");
    }
    Ok(out)
}

/// `minecraft:grass_block` becomes `GRASS_BLOCK`, `minecraft:debug/event` becomes `DEBUG_EVENT`.
fn constant_name(identifier: &str) -> Result<String> {
    let name = identifier.strip_prefix("minecraft:").unwrap_or(identifier);
    let name = name.replace('/', "_");
    let valid = name.starts_with(|c: char| c.is_ascii_lowercase() || c == '_')
        && name
            .chars()
            .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '_');
    ensure!(valid, "{identifier} cannot be turned into a constant name");
    Ok(name.to_ascii_uppercase())
}

/// Comma-separated numbers, wrapped to the line width, each line starting with `indent`.
fn wrapped(numbers: &[usize], indent: &str) -> String {
    let mut out = String::new();
    let mut line = String::new();
    for number in numbers {
        let item = format!("{number},");
        if !line.is_empty() && indent.len() + line.len() + 1 + item.len() > LINE_WIDTH {
            out.push_str(indent);
            out.push_str(&line);
            out.push('\n');
            line.clear();
        }
        if !line.is_empty() {
            line.push(' ');
        }
        line.push_str(&item);
    }
    if !line.is_empty() {
        out.push_str(indent);
        out.push_str(&line);
        out.push('\n');
    }
    out
}
